const tracks = [
    { id: 1, title: 'Audio No. 1', artist: 'SynthWave Hero', category: 'Synthwave', length: '03:45', bestFor: 'Couples' },
    { id: 2, title: 'Audio No. 2', artist: 'Neon Pulse', category: 'Electronic', length: '04:10', bestFor: 'Men' },
    { id: 3, title: 'Audio No. 3', artist: 'Pixel Beats', category: 'Chiptune', length: '02:50', bestFor: 'Women' },
    { id: 4, title: 'Audio No. 4', artist: 'Cyberwave', category: 'Ambient', length: '05:20', bestFor: 'Nonbinary' },
    { id: 5, title: 'Audio No. 5', artist: 'Synthwave Nights', category: 'Synthwave', length: '04:30', bestFor: 'Couples' },
    { id: 6, title: 'Audio No. 6', artist: 'Future Sound', category: 'Electronic', length: '03:00', bestFor: 'Men' },
    { id: 7, title: 'Audio No. 7', artist: '8Bit Maestro', category: 'Chiptune', length: '03:15', bestFor: 'Women' },
    { id: 8, title: 'Audio No. 8', artist: 'Lunar Tone', category: 'Ambient', length: '04:40', bestFor: 'Nonbinary' },
    { id: 9, title: 'Audio No. 9', artist: 'Neon Lovers', category: 'Synthwave', length: '04:00', bestFor: 'Couples' },
    { id: 10, title: 'Audio No. 10', artist: 'Cyber Pulse', category: 'Electronic', length: '03:30', bestFor: 'Men' },
    { id: 11, title: 'Audio No. 11', artist: 'Retro Vibes', category: 'Chiptune', length: '03:05', bestFor: 'Women' },
    { id: 12, title: 'Audio No. 12', artist: 'Zenith Sound', category: 'Ambient', length: '05:00', bestFor: 'Nonbinary' },
    { id: 13, title: 'Audio No. 13', artist: '8Bit Pulse', category: 'Chiptune', length: '03:20', bestFor: 'Couples' },
    { id: 14, title: 'Audio No. 14', artist: 'Neon Flow', category: 'Electronic', length: '04:15', bestFor: 'Men' },
    { id: 15, title: 'Audio No. 15', artist: 'Starwave', category: 'Ambient', length: '05:30', bestFor: 'Nonbinary' },
    { id: 16, title: 'Audio No. 16', artist: 'SynthDreamer', category: 'Synthwave', length: '03:50', bestFor: 'Couples' },
    { id: 17, title: 'Audio No. 17', artist: 'RetroX', category: 'Electronic', length: '04:05', bestFor: 'Men' },
    { id: 18, title: 'Audio No. 18', artist: 'Digital Rush', category: 'Chiptune', length: '03:25', bestFor: 'Women' },
    { id: 19, title: 'Audio No. 19', artist: 'NightSky', category: 'Ambient', length: '04:50', bestFor: 'Nonbinary' },
    { id: 20, title: 'Audio No. 20', artist: 'Neon Pulse', category: 'Synthwave', length: '04:20', bestFor: 'Couples' },
    { id: 21, title: 'Audio No. 21', artist: 'Sonic Vision', category: 'Electronic', length: '03:40', bestFor: 'Men' },
    { id: 22, title: 'Audio No. 22', artist: 'Chiptune Kings', category: 'Chiptune', length: '03:10', bestFor: 'Women' },
    { id: 23, title: 'Audio No. 23', artist: 'Neon Lights', category: 'Synthwave', length: '04:30', bestFor: 'Couples' },
    { id: 24, title: 'Audio No. 24', artist: 'Pixel Path', category: 'Electronic', length: '03:55', bestFor: 'Men' },
    { id: 25, title: 'Audio No. 25', artist: 'Digital Dreamers', category: 'Chiptune', length: '03:00', bestFor: 'Women' },
    { id: 26, title: 'Audio No. 26', artist: 'Stellar Sounds', category: 'Ambient', length: '04:10', bestFor: 'Nonbinary' },
    { id: 27, title: 'Audio No. 27', artist: 'RetroVision', category: 'Synthwave', length: '04:00', bestFor: 'Couples' },
    { id: 28, title: 'Audio No. 28', artist: 'SynthDrive', category: 'Electronic', length: '03:30', bestFor: 'Men' },
    { id: 29, title: 'Audio No. 29', artist: '8Bit Realm', category: 'Chiptune', length: '03:20', bestFor: 'Women' },
    { id: 30, title: 'Audio No. 30', artist: 'Celestial Waves', category: 'Ambient', length: '05:00', bestFor: 'Nonbinary' },
]

export default tracks;