const tracks = [
    { id: 1, title: 'Eternal Love', artist: 'SynthWave Hero', category: 'Synthwave', length: '03:45', bestFor: 'Couples' },
    { id: 2, title: 'Night Drive', artist: 'Neon Pulse', category: 'Electronic', length: '04:10', bestFor: 'Men' },
    { id: 3, title: 'Dreamscape', artist: 'Pixel Beats', category: 'Chiptune', length: '02:50', bestFor: 'Women' },
    { id: 4, title: 'Digital Serenity', artist: 'Cyberwave', category: 'Ambient', length: '05:20', bestFor: 'Nonbinary' },
    { id: 5, title: 'Retro Love', artist: 'Synthwave Nights', category: 'Synthwave', length: '04:30', bestFor: 'Couples' },
    { id: 6, title: 'Electric Dreams', artist: 'Future Sound', category: 'Electronic', length: '03:00', bestFor: 'Men' },
    { id: 7, title: 'Pixelated Memories', artist: '8Bit Maestro', category: 'Chiptune', length: '03:15', bestFor: 'Women' },
    { id: 8, title: 'Moonlit Voyage', artist: 'Lunar Tone', category: 'Ambient', length: '04:40', bestFor: 'Nonbinary' },
    { id: 9, title: 'Synthwave Hearts', artist: 'Neon Lovers', category: 'Synthwave', length: '04:00', bestFor: 'Couples' },
    { id: 10, title: 'Neon Nightmares', artist: 'Cyber Pulse', category: 'Electronic', length: '03:30', bestFor: 'Men' },
    { id: 11, title: 'Glitch in Time', artist: 'Retro Vibes', category: 'Chiptune', length: '03:05', bestFor: 'Women' },
    { id: 12, title: 'Ambient Reflections', artist: 'Zenith Sound', category: 'Ambient', length: '05:00', bestFor: 'Nonbinary' },
    { id: 13, title: 'Pixelated Dreams', artist: '8Bit Pulse', category: 'Chiptune', length: '03:20', bestFor: 'Couples' },
    { id: 14, title: 'Electric Haze', artist: 'Neon Flow', category: 'Electronic', length: '04:15', bestFor: 'Men' },
    { id: 15, title: 'Cosmic Bliss', artist: 'Starwave', category: 'Ambient', length: '05:30', bestFor: 'Nonbinary' },
    { id: 16, title: 'Synth Love Story', artist: 'SynthDreamer', category: 'Synthwave', length: '03:50', bestFor: 'Couples' },
    { id: 17, title: 'Future Pulse', artist: 'RetroX', category: 'Electronic', length: '04:05', bestFor: 'Men' },
    { id: 18, title: 'Pixel Playgrounds', artist: 'Digital Rush', category: 'Chiptune', length: '03:25', bestFor: 'Women' },
    { id: 19, title: 'Ambient Echoes', artist: 'NightSky', category: 'Ambient', length: '04:50', bestFor: 'Nonbinary' },
    { id: 20, title: 'Retro Dreams', artist: 'Neon Pulse', category: 'Synthwave', length: '04:20', bestFor: 'Couples' },
    { id: 21, title: 'Neon Skies', artist: 'Sonic Vision', category: 'Electronic', length: '03:40', bestFor: 'Men' },
    { id: 22, title: 'Pixel Heartbeat', artist: 'Chiptune Kings', category: 'Chiptune', length: '03:10', bestFor: 'Women' },
    { id: 23, title: 'Future Horizons', artist: 'Neon Lights', category: 'Synthwave', length: '04:30', bestFor: 'Couples' },
    { id: 24, title: 'Digital Glow', artist: 'Pixel Path', category: 'Electronic', length: '03:55', bestFor: 'Men' },
    { id: 25, title: 'Pixel Dreams', artist: 'Digital Dreamers', category: 'Chiptune', length: '03:00', bestFor: 'Women' },
    { id: 26, title: 'Cosmic Flight', artist: 'Stellar Sounds', category: 'Ambient', length: '04:10', bestFor: 'Nonbinary' },
    { id: 27, title: 'Synthwave Pulse', artist: 'RetroVision', category: 'Synthwave', length: '04:00', bestFor: 'Couples' },
    { id: 28, title: 'Retro Vibes', artist: 'SynthDrive', category: 'Electronic', length: '03:30', bestFor: 'Men' },
    { id: 29, title: 'Pixel Adventure', artist: '8Bit Realm', category: 'Chiptune', length: '03:20', bestFor: 'Women' },
    { id: 30, title: 'Starry Dreams', artist: 'Celestial Waves', category: 'Ambient', length: '05:00', bestFor: 'Nonbinary' },
]

export default tracks;